# Generated by Django 5.2.14 on 2026-06-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_answer_question_alter_answer_response"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="response",
            unique_together={("form", "email")},
        ),
    ]
