# Generated by Django 5.2.14 on 2026-06-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_response_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="sentiment",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="response",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
