# Generated by Django 5.2.14 on 2026-06-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_alter_answer_response_additionalfield_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="sentiment",
        ),
        migrations.RemoveField(
            model_name="response",
            name="sentiment_score",
        ),
    ]
